server.port=30000
spring.datasource.url=jdbc:mysql://192.168.1.115:9030/test
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=admin
spring.datasource.password=alexgaoyh
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema-mysql.sql
spring.sql.init.data-locations=classpath:data-mysql.sql
mybatis-plus.global-config.enable-sql-runner=true
mybatis-plus.mapper-locations=classpath*:cn/net/pap/example/doris/**/xml/*Mapper.xml
##logging.level.org.=trace