server.port=30000
## Bolt?Neo4j????????????????????????Bolt 3.x????????????????????????????????????????system?????????Cypher???USE????????????
## spring.data.neo4j.database=neo4j
spring.neo4j.uri=bolt://127.0.0.1:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=alexgaoyh
logging.level.org=debug
