ftp.port=21
ftp.connectRateLimit=25
ftp.users[0].username=bj
ftp.users[0].password=123456
ftp.users[0].homeDirectory=d:/knowledge
ftp.users[1].username=admin1
ftp.users[1].password=123456
ftp.users[1].homeDirectory=d:/ftp/user1
ftp.users[2].username=admin2
ftp.users[2].password=123456
ftp.users[2].homeDirectory=d:/ftp/user2

#logging.level.org.apache.ftpserver=ERROR
#logging.level.org.apache.ftplet=ERROR
#logging.level.org.apache.mina=ERROR
#
#logging.level.root=WARN
#
#logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n