ftp.port=2121
ftp.users[0].username=admin
ftp.users[0].password=123456
ftp.users[0].homeDirectory=d:/knowledge
ftp.users[1].username=admin1
ftp.users[1].password=123456
ftp.users[1].homeDirectory=d:/ftp/user1
ftp.users[2].username=admin2
ftp.users[2].password=123456
ftp.users[2].homeDirectory=d:/ftp/user2
