spring:
  web:
    resources:
      static-locations:
        file:D:/pap/
  messages:
    encoding: utf-8
    basename: i18n/messages

# Springdoc配置
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
  group-configs:
    - group: 'default'
      display-name: '测试模块'
      paths-to-match: '/**'
      packages-to-scan: cn.net.pap.example.admin
    - group: 'front'
      display-name: '前台接口'
      packages-to-scan: cn.net.pap.example.admin.controller.front
    - group: 'back'
      display-name: '后台接口'
      packages-to-scan: cn.net.pap.example.admin.controller.back
    - group: 'third'
      display-name: '第三方接口'
      packages-to-scan: cn.net.pap.example.admin.controller.third
