server.port=30000

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=3600s

spring.datasource.url=jdbc:h2:mem:pap4j-boot3-example-proguard;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.hikari.leak-detection-threshold=3000
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
snowflake.workerId=10
snowflake.datacenterId=10
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.session_factory.statement_inspector=cn.net.pap.example.proguard.config.PapStatementInspector
logging.level.org.hibernate.orm.jdbc.bind=trace
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=trace
logging.level.com.zaxxer.hikari.pool.ProxyLeakTask: WARN

spring.jpa.properties.hibernate.session.events.log.LOG_QUERIES_SLOWER_THAN_MS=25

spring.jpa.properties.hibernate.multiTenancy=discriminator
spring.jpa.properties.hibernate.tenant_identifier_resolver=cn.net.pap.example.proguard.config.PapTenantIdentifierResolver

spring.profiles.active=dev
demo.intercept.read-prefixes=get,find,query,list,count,select,read,fetch,load
demo.intercept.write-prefixes=save,update,delete,create,remove,add,modify,change
demo.intercept.enable-detail-log=true
demo.intercept.mark-demo-data=true
demo.intercept.success-message="????: ???????"