server:
  port: 30000
logging:
  level:
    root: INFO
security:
  basic:
    enabled: false
spring:
  datasource:
    url: jdbc:sqlite:file::memory:?cache=shared
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
